import type { Metadata } from "next";
import { Bangers } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bangers = Bangers({
  weight: ["400"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ margin: 0, padding: 0, height: "100vh", overflow: "hidden" }}
      >
        {children} {}
      </body>
    </html>
  );
}

//<html>
// <body>
//   <nav>
//    <h1>Nav Bar</h1>
//  <ul>
//  {" "}
//<li>
// <a href="/"> Home</a>
//</li>
//<li>
// <a href="/superheros">Superheros</a>
//</li>
//</ul>
// </nav>

// {children}
//  </body>
//  </html>
